# Generated by Django 2.1.1 on 2018-09-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('article_url', models.CharField(max_length=200)),
                ('article_title', models.CharField(max_length=20)),
                ('article_text', models.TextField()),
                ('article_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_text', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('article', models.ManyToManyField(to='app.Article')),
            ],
        ),
    ]
