# Generated by Django 2.1.1 on 2018-09-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_sim',
            field=models.CharField(default=123, max_length=300),
            preserve_default=False,
        ),
    ]
